# https://dockerlabs.collabnix.com/kubernetes/beginners/Install-and-configure-a-multi-master-Kubernetes-cluster-with-kubeadm.html

IMAGE_NAME = "bento/ubuntu-16.04"
M = 3
N = 3


Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.define "haproxy-lb" do |proxy|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "172.16.0.9"
        master.vm.hostname = "haproxy-lb"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "kubernetes-setup/haproxy-playbook.yml"
            ansible.extra_vars = {
                node_ip: "172.16.0.9",
            }
        end
    end

    (1..M).each do |i|
        config.vm.define "master-#{i}" do |master|
            master.vm.box = IMAGE_NAME
            master.vm.network "private_network", ip: "172.16.0.#{i + 9}"
            master.vm.hostname = "master-#{i}"
            master.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/master-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "172.16.0.#{i + 9}",
                    kube_user: "vagrant",
                }
            end
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "172.16.0.#{i + 12}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "kubernetes-setup/node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "172.16.0.#{i + 10}",
                }
            end
        end
    end
    
end

