---
- hosts: all
  become: true
  tasks:

# Step 1: Install Docker and its dependent components.

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

# Step 2: Installing haproxy

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - haproxy

# Step 3: Configure HAProxy to load balance the traffic between the three Kubernetes master nodes.


# Step 4: Restart HAProxy

